# YAML syntax https://rollout.io/blog/yaml-tutorial-everything-you-need-get-started/
version: '2.0'
services:
    demo:
        container_name: demo
        build: ./demo # will use demo/Dockerfile
        environment:
            - MEMCACHED_ADDR=cache:11211
        ports:
            - "3000:80" # http://localhost:3000/ -> http://demo:80/
        # Volumes can be added for live-reloading during development
        volumes:
            - "./demo/src:/var/www/html/" # automaticaly sync local changes to Docker container

    cdn:
        container_name: cdn
        build: ./cdn # will use cdn/Dockerfile
        ports:
            - "3001:80" # http://localhost:3001/ -> http://cdn:80/
        # Volumes can be added for live-reloading during development
        volumes:
            - "./cdn/client:/usr/share/nginx/html" # automaticaly sync local changes to Docker container

    load-balancer:
        container_name: load-balancer
        build: ./load-balancer # will use load-balancer/Dockerfile
        ports:
            - "3002:80" # http://localhost:3002/ -> http://load-balancer:80/

    app-server1:
        container_name: app-server1
        build: ./app-server # will use app-server/Dockerfile
        environment:
            - APP_SERVER_HOSTNAME=app-server1
            - MEMCACHED_ADDR=cache:11211
        ports:
            - "8000" # allow other containers to connect
            - "3003:8000" # http://localhost:3003/ -> http://app-server:8000/
        # Volumes can be added for live-reloading during development
        volumes:
            - "./app-server/src:/usr/local/app-server/src" # automaticaly sync local changes to Docker container

    app-server2:
        container_name: app-server2
        build: ./app-server # will use app-server/Dockerfile
        environment:
            - APP_SERVER_HOSTNAME=app-server2
            - MEMCACHED_ADDR=cache:11211
        ports:
            - "8000" # allow other containers to connect
            - "3004:8000" # http://localhost:3004/ -> http://app-server:8000/
        # Volumes can be added for live-reloading during development
        volumes:
            - "./app-server/src:/usr/local/app-server/src" # automaticaly sync local changes to Docker container

    cache:
        container_name: cache
        build: ./cache # will use cache/Dockerfile
        ports:
            - "11211" # allow other containers to connect
            - "3005:11211" # telnet localhost 3005 -> telnet cache 11211
